name: academic_system
description: A School Academic Information System
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0-290.4.beta
  flutter: "3.38.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  sqflite: ^2.3.0
  path: ^1.8.3
  pdf: ^3.10.4
  printing: ^5.11.0
  shared_preferences: ^2.2.2
  fl_chart: ^0.64.0
  intl: ^0.18.1
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/